#!/bin/bash

stra.jar -d -f vault.key.stra > vault.key
cp vault.key roles/jenkins_deploy/files/vault.key

ANSIBLE_STDOUT_CALLBACK=debug ansible-playbook --vault-password-file vault.key $@

rm vault.key
rm roles/jenkins_deploy/files/vault.key
